# Generated by Django 5.2.17 on 2026-09-10 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("championships", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="championshipstaff",
            name="championship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff",
                to="championships.championship",
            ),
        ),
        migrations.AddField(
            model_name="championshipstaff",
            name="divisions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Vide = toutes les divisions de l'édition.",
                related_name="staff",
                to="championships.division",
            ),
        ),
        migrations.AddField(
            model_name="championshipstaff",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_roles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="championshipstaff",
            constraint=models.UniqueConstraint(
                fields=("championship", "user", "role"),
                name="uniq_staff_role_per_championship",
            ),
        ),
    ]
