# Generated by Django 5.2.17 on 2026-09-10 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("championships", "0001_initial"),
        ("competition", "0001_initial"),
        ("participations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StandingSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="créé le"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
                ("is_current", models.BooleanField(db_index=True, default=False)),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tiebreak_primary_used",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SCORE_DIFF", "Différence de score"),
                            ("HEAD_TO_HEAD", "Confrontation directe"),
                        ],
                        max_length=16,
                    ),
                ),
                ("has_unresolved_tie", models.BooleanField(default=False)),
                (
                    "as_of_matchday",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vide = état courant.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="standing_snapshots",
                        to="competition.matchday",
                    ),
                ),
                (
                    "championship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standing_snapshots",
                        to="championships.championship",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standing_snapshots",
                        to="championships.division",
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standing_snapshots",
                        to="competition.phase",
                    ),
                ),
            ],
            options={
                "verbose_name": "instantané de classement",
                "verbose_name_plural": "instantanés de classement",
                "ordering": ["-computed_at"],
            },
        ),
        migrations.CreateModel(
            name="StandingRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="créé le"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
                ("rank", models.PositiveIntegerField()),
                ("played", models.PositiveIntegerField(default=0)),
                ("wins", models.PositiveIntegerField(default=0)),
                ("draws", models.PositiveIntegerField(default=0)),
                ("losses", models.PositiveIntegerField(default=0)),
                ("points", models.IntegerField(default=0)),
                ("score_for", models.IntegerField(default=0)),
                ("score_against", models.IntegerField(default=0)),
                ("score_diff", models.IntegerField(default=0)),
                (
                    "win_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("form", models.JSONField(blank=True, default=list)),
                ("tie_group", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "movement_zone",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PROMOTION", "Promotion"),
                            ("FINALS", "Qualification phase finale"),
                            ("SAFE", "Maintien"),
                            ("RELEGATION", "Relégation"),
                        ],
                        max_length=12,
                    ),
                ),
                ("rank_change", models.IntegerField(default=0)),
                ("movement_probabilities", models.JSONField(blank=True, null=True)),
                (
                    "participation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standing_rows",
                        to="participations.championshipparticipation",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="rankings.standingsnapshot",
                    ),
                ),
            ],
            options={
                "verbose_name": "ligne de classement",
                "verbose_name_plural": "lignes de classement",
                "ordering": ["snapshot", "rank"],
            },
        ),
        migrations.AddConstraint(
            model_name="standingsnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("division", "phase"),
                name="uniq_current_snapshot_per_division_phase",
            ),
        ),
        migrations.AddConstraint(
            model_name="standingrow",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "participation"),
                name="uniq_row_per_snapshot_participation",
            ),
        ),
    ]
