# Generated by Django 5.2.17 on 2026-09-10 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("championships", "0001_initial"),
        ("participations", "0001_initial"),
        ("players", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SeasonTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="créé le"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposée"),
                            ("ADJUSTED", "Ajustée"),
                            ("CONFIRMED", "Confirmée"),
                            ("CANCELLED", "Annulée"),
                        ],
                        default="PROPOSED",
                        max_length=12,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transitions_confirmed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transitions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_championship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transitions_out",
                        to="championships.championship",
                    ),
                ),
                (
                    "to_championship",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transitions_in",
                        to="championships.championship",
                    ),
                ),
            ],
            options={
                "verbose_name": "transition de saison",
                "verbose_name_plural": "transitions de saison",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SeasonTransitionMove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="créé le"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
                ("from_carryover_key", models.SlugField(max_length=40)),
                ("to_carryover_key", models.SlugField(blank=True, max_length=40)),
                (
                    "move_type",
                    models.CharField(
                        choices=[
                            ("PROMOTED", "Promu"),
                            ("RELEGATED", "Relégué"),
                            ("KEPT", "Maintenu"),
                            ("MANUAL_OVERRIDE", "Ajustement manuel"),
                            ("NEW", "Nouvel inscrit"),
                            ("WITHDRAWN", "Retiré"),
                        ],
                        max_length=16,
                    ),
                ),
                ("is_manual_override", models.BooleanField(default=False)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transition_moves",
                        to="players.player",
                    ),
                ),
                (
                    "source_participation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transition_moves",
                        to="participations.championshipparticipation",
                    ),
                ),
                (
                    "transition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moves",
                        to="transitions.seasontransition",
                    ),
                ),
            ],
            options={
                "verbose_name": "mouvement de transition",
                "verbose_name_plural": "mouvements de transition",
                "ordering": ["transition", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("transition", "source_participation"),
                        name="uniq_move_per_participation",
                    )
                ],
            },
        ),
    ]
