# Generated by Django 5.2.17 on 2026-09-10 21:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetitionSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="créé le"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
                ("name", models.CharField(max_length=160, verbose_name="nom")),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "organizer",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="organisateur"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "série de compétitions",
                "verbose_name_plural": "séries de compétitions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Championship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="créé le"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
                ("name", models.CharField(max_length=180, verbose_name="nom")),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "season",
                    models.CharField(
                        help_text="Ex. « 2026 ».", max_length=40, verbose_name="saison"
                    ),
                ),
                (
                    "edition_number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="numéro d'édition"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="date de début"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="date de fin"),
                ),
                (
                    "registration_opens_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ouverture des inscriptions"
                    ),
                ),
                (
                    "registration_closes_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="clôture des inscriptions"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("CONFIGURING", "Configuration"),
                            ("REGISTRATION_OPEN", "Inscriptions ouvertes"),
                            ("SCHEDULED", "Calendrier généré"),
                            ("IN_PROGRESS", "En cours"),
                            ("FINALS", "Phase finale"),
                            ("COMPLETED", "Terminé"),
                            ("ARCHIVED", "Archivé"),
                            ("CANCELLED", "Annulé"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "is_inaugural",
                    models.BooleanField(
                        default=False,
                        help_text="Tous les joueurs peuvent démarrer dans la division inférieure.",
                        verbose_name="édition inaugurale",
                    ),
                ),
                (
                    "rules_locked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="règles verrouillées le"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="championships_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "previous_edition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="next_editions",
                        to="championships.championship",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="editions",
                        to="championships.competitionseries",
                    ),
                ),
            ],
            options={
                "verbose_name": "championnat",
                "verbose_name_plural": "championnats",
                "ordering": ["-season", "name"],
            },
        ),
        migrations.CreateModel(
            name="ChampionshipSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="créé le"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
                (
                    "points_win",
                    models.IntegerField(default=3, verbose_name="points victoire"),
                ),
                (
                    "points_draw",
                    models.IntegerField(default=1, verbose_name="points nul"),
                ),
                (
                    "points_loss",
                    models.IntegerField(default=0, verbose_name="points défaite"),
                ),
                (
                    "points_forfeit_win",
                    models.IntegerField(
                        default=3, verbose_name="points victoire par forfait"
                    ),
                ),
                (
                    "points_forfeit_loss",
                    models.IntegerField(
                        default=0, verbose_name="points défaite par forfait"
                    ),
                ),
                (
                    "forfeit_score_for",
                    models.PositiveIntegerField(
                        default=0,
                        verbose_name="score attribué au vainqueur sur forfait",
                    ),
                ),
                (
                    "forfeit_score_against",
                    models.PositiveIntegerField(
                        default=0, verbose_name="score attribué au perdant sur forfait"
                    ),
                ),
                (
                    "primary_tiebreak",
                    models.CharField(
                        choices=[
                            ("SCORE_DIFF", "Différence de score"),
                            ("HEAD_TO_HEAD", "Confrontation directe"),
                        ],
                        default="SCORE_DIFF",
                        max_length=16,
                        verbose_name="départage principal",
                    ),
                ),
                (
                    "round_robin_legs",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="nombre de confrontations (aller / aller-retour)",
                    ),
                ),
                (
                    "result_entry_policy",
                    models.CharField(
                        choices=[
                            ("WINNER_ONLY", "Vainqueur uniquement"),
                            ("BOTH_PLAYERS", "Les deux joueurs"),
                            ("ADMIN_ONLY", "Administrateur uniquement"),
                        ],
                        default="WINNER_ONLY",
                        max_length=16,
                    ),
                ),
                ("result_confirmation_required", models.BooleanField(default=True)),
                (
                    "double_entry_auto_confirm",
                    models.BooleanField(
                        default=True,
                        verbose_name="confirmation automatique si deux saisies identiques",
                    ),
                ),
                (
                    "late_match_threshold_days",
                    models.PositiveSmallIntegerField(
                        default=3, verbose_name="seuil « match en retard » (jours)"
                    ),
                ),
                (
                    "finals_enabled",
                    models.BooleanField(
                        default=False, verbose_name="phase finale activée"
                    ),
                ),
                (
                    "finals_qualifiers_count",
                    models.PositiveSmallIntegerField(
                        default=4, verbose_name="nombre de qualifiés par division"
                    ),
                ),
                (
                    "finals_format",
                    models.CharField(
                        choices=[
                            ("SEMI_1V4_2V3", "Demi-finales 1v4 / 2v3"),
                            ("KNOCKOUT", "Élimination directe (têtes de série)"),
                            ("CUSTOM", "Personnalisé"),
                        ],
                        default="SEMI_1V4_2V3",
                        max_length=20,
                    ),
                ),
                (
                    "finals_third_place",
                    models.BooleanField(default=True, verbose_name="petite finale"),
                ),
                (
                    "carry_over_between_editions",
                    models.BooleanField(
                        default=True,
                        verbose_name="gérer promotions / relégations vers l'édition suivante",
                    ),
                ),
                (
                    "championship",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="championships.championship",
                    ),
                ),
            ],
            options={
                "verbose_name": "configuration du championnat",
                "verbose_name_plural": "configurations des championnats",
            },
        ),
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="créé le"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
                ("name", models.CharField(max_length=80, verbose_name="nom")),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        help_text="1 = élite. Détermine la hiérarchie.",
                        verbose_name="niveau",
                    ),
                ),
                (
                    "carryover_key",
                    models.SlugField(
                        help_text="Clé stable d'une édition à l'autre (ex. « d1 »).",
                        max_length=40,
                        verbose_name="clé inter-éditions",
                    ),
                ),
                (
                    "capacity_min",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="capacité minimale"
                    ),
                ),
                (
                    "capacity_max",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Vide = illimitée.",
                        null=True,
                        verbose_name="capacité maximale",
                    ),
                ),
                (
                    "is_unlimited",
                    models.BooleanField(
                        default=False, verbose_name="capacité illimitée"
                    ),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=20, verbose_name="couleur"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("params", models.JSONField(blank=True, default=dict)),
                (
                    "championship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="divisions",
                        to="championships.championship",
                    ),
                ),
            ],
            options={
                "verbose_name": "division",
                "verbose_name_plural": "divisions",
                "ordering": ["championship", "level"],
            },
        ),
        migrations.CreateModel(
            name="PromotionRelegationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="créé le"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("PROMOTION", "Promotion"),
                            ("RELEGATION", "Relégation"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("TOP_N", "N premiers"),
                            ("BOTTOM_N", "N derniers"),
                            ("TOP_PERCENTAGE", "Pourcentage supérieur"),
                            ("BOTTOM_PERCENTAGE", "Pourcentage inférieur"),
                            ("RANK_RANGE", "Plage de classement"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "value_n",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="valeur N"
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="pourcentage",
                    ),
                ),
                (
                    "rank_min",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="rang minimum"
                    ),
                ),
                (
                    "rank_max",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="rang maximum"
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="priorité"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "championship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movement_rules",
                        to="championships.championship",
                    ),
                ),
                (
                    "source_division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movement_rules_out",
                        to="championships.division",
                    ),
                ),
                (
                    "target_division",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vide = sortie de la structure / maintien hors division.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movement_rules_in",
                        to="championships.division",
                    ),
                ),
            ],
            options={
                "verbose_name": "règle de promotion / relégation",
                "verbose_name_plural": "règles de promotion / relégation",
                "ordering": ["championship", "priority"],
            },
        ),
        migrations.CreateModel(
            name="ChampionshipTiebreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="créé le"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        verbose_name="ordre d'application"
                    ),
                ),
                (
                    "criterion",
                    models.CharField(
                        choices=[
                            ("SCORE_DIFF", "Différence de score"),
                            ("HEAD_TO_HEAD", "Confrontation directe"),
                            ("WINS", "Nombre de victoires"),
                            ("SCORE_FOR", "Score total marqué"),
                            ("SCORE_AGAINST_ASC", "Score total encaissé (croissant)"),
                            ("FORM", "Forme récente"),
                            ("SEED", "Tête de série"),
                            ("DRAW_LOTS", "Tirage au sort"),
                            ("MANUAL", "Décision de l'arbitre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "championship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiebreaks",
                        to="championships.championship",
                    ),
                ),
            ],
            options={
                "verbose_name": "critère de départage",
                "verbose_name_plural": "critères de départage",
                "ordering": ["championship", "position"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("championship", "position"),
                        name="uniq_tiebreak_position",
                    ),
                    models.UniqueConstraint(
                        fields=("championship", "criterion"),
                        name="uniq_tiebreak_criterion",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="championship",
            constraint=models.UniqueConstraint(
                fields=("series", "season"), name="uniq_season_per_series"
            ),
        ),
        migrations.AddConstraint(
            model_name="division",
            constraint=models.UniqueConstraint(
                fields=("championship", "level"), name="uniq_division_level"
            ),
        ),
        migrations.AddConstraint(
            model_name="division",
            constraint=models.UniqueConstraint(
                fields=("championship", "name"), name="uniq_division_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="division",
            constraint=models.UniqueConstraint(
                fields=("championship", "carryover_key"), name="uniq_division_carryover"
            ),
        ),
        migrations.AddConstraint(
            model_name="division",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("capacity_min__isnull", True),
                    ("capacity_max__isnull", True),
                    ("capacity_max__gte", models.F("capacity_min")),
                    _connector="OR",
                ),
                name="division_capacity_min_lte_max",
            ),
        ),
        migrations.AddConstraint(
            model_name="promotionrelegationrule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source_division", models.F("target_division")), _negated=True
                ),
                name="movement_source_ne_target",
            ),
        ),
    ]
