# Generated by Django 5.2.17 on 2026-09-11 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("championships", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="championship",
            name="previous_edition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_editions",
                to="championships.championship",
                verbose_name="édition précédente",
            ),
        ),
        migrations.AlterField(
            model_name="championship",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="editions",
                to="championships.competitionseries",
                verbose_name="série",
            ),
        ),
    ]
