# Generated by Django 5.2.17 on 2026-09-11 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("championships", "0002_alter_championship_previous_edition_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="championshiptiebreak",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
        migrations.AlterField(
            model_name="promotionrelegationrule",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
        migrations.AlterField(
            model_name="promotionrelegationrule",
            name="method",
            field=models.CharField(
                choices=[
                    ("TOP_N", "N premiers"),
                    ("BOTTOM_N", "N derniers"),
                    ("TOP_PERCENTAGE", "Pourcentage supérieur"),
                    ("BOTTOM_PERCENTAGE", "Pourcentage inférieur"),
                    ("RANK_RANGE", "Plage de classement"),
                ],
                max_length=20,
                verbose_name="méthode",
            ),
        ),
        migrations.AlterField(
            model_name="promotionrelegationrule",
            name="movement_type",
            field=models.CharField(
                choices=[("PROMOTION", "Promotion"), ("RELEGATION", "Relégation")],
                max_length=12,
                verbose_name="type de mouvement",
            ),
        ),
        migrations.AlterField(
            model_name="promotionrelegationrule",
            name="source_division",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movement_rules_out",
                to="championships.division",
                verbose_name="division source",
            ),
        ),
        migrations.AlterField(
            model_name="promotionrelegationrule",
            name="target_division",
            field=models.ForeignKey(
                blank=True,
                help_text="Vide = sortie de la structure / maintien hors division.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movement_rules_in",
                to="championships.division",
                verbose_name="division destination",
            ),
        ),
    ]
