# Generated by Django 5.2.17 on 2026-09-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("championships", "0003_alter_championshiptiebreak_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="championshipsettings",
            name="finals_format",
            field=models.CharField(
                choices=[
                    ("SEMI_1V4_2V3", "Demi-finales 1v4 / 2v3"),
                    ("KNOCKOUT", "Élimination directe (têtes de série)"),
                    ("CUSTOM", "Personnalisé"),
                ],
                default="SEMI_1V4_2V3",
                max_length=20,
                verbose_name="format de la phase finale",
            ),
        ),
        migrations.AlterField(
            model_name="championshipsettings",
            name="result_confirmation_required",
            field=models.BooleanField(
                default=True, verbose_name="confirmation du résultat requise"
            ),
        ),
        migrations.AlterField(
            model_name="championshipsettings",
            name="result_entry_policy",
            field=models.CharField(
                choices=[
                    ("WINNER_ONLY", "Vainqueur uniquement"),
                    ("BOTH_PLAYERS", "Les deux joueurs"),
                    ("ADMIN_ONLY", "Administrateur uniquement"),
                ],
                default="WINNER_ONLY",
                max_length=16,
                verbose_name="politique de saisie des résultats",
            ),
        ),
    ]
