# Generated by Django 5.2.17 on 2026-09-15 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("championships", "0004_alter_championshipsettings_finals_format_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promotionrelegationrule",
            name="source_division",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="movement_rules_out",
                to="championships.division",
                verbose_name="division source",
            ),
        ),
        migrations.AlterField(
            model_name="promotionrelegationrule",
            name="target_division",
            field=models.ForeignKey(
                blank=True,
                help_text="Vide = sortie de la structure / maintien hors division.",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="movement_rules_in",
                to="championships.division",
                verbose_name="division destination",
            ),
        ),
    ]
