# Generated by Django 5.2.17 on 2026-09-23 21:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "championships",
            "0005_alter_promotionrelegationrule_source_division_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="championshipsettings",
            name="max_matches_per_day",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Vide = pas de limite. Une fois ce nombre de matchs joué dans la journée, le prochain adversaire n'est plus dévoilé au joueur avant le lendemain.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="matchs maximum par jour et par joueur",
            ),
        ),
    ]
