# Generated by Django 5.2.17 on 2026-09-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("championships", "0006_settings_max_matches_per_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="championshipsettings",
            name="late_match_threshold_days",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Nombre de jours de grâce après la date prévue. 0 = un match non joué est en retard dès le lendemain de sa date prévue.",
                verbose_name="tolérance avant « match en retard » (jours)",
            ),
        ),
    ]
