# Generated by Django 5.2.17 on 2026-09-25 08:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("championships", "0007_late_threshold_default_zero"),
    ]

    operations = [
        migrations.AddField(
            model_name="championshipsettings",
            name="upcoming_matches_shown",
            field=models.PositiveSmallIntegerField(
                default=2,
                help_text="Nombre de prochains matchs montrés à chaque joueur dans « Mon espace ». Si une limite de matchs par jour est définie, l'affichage ne dépasse jamais ce qu'il reste à jouer aujourd'hui.",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="prochains matchs affichés par joueur",
            ),
        ),
    ]
