# Generated by Django 5.2.17 on 2026-09-25 08:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("championships", "0008_settings_upcoming_matches_shown"),
    ]

    operations = [
        migrations.AlterField(
            model_name="championshipsettings",
            name="upcoming_matches_shown",
            field=models.PositiveSmallIntegerField(
                default=2,
                help_text="Nombre de prochains matchs montrés à chaque joueur dans « Mon espace ». Ne s'applique que sans limite de matchs par jour : avec une limite, tous les matchs de la journée sont dévoilés (autant que la limite) et jamais davantage.",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="prochains matchs affichés par joueur",
            ),
        ),
    ]
