# Generated by Django 5.2.17 on 2026-09-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("championships", "0009_upcoming_shown_help_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="championshiptiebreak",
            name="criterion",
            field=models.CharField(
                choices=[
                    ("SCORE_DIFF", "Différence de score"),
                    ("HEAD_TO_HEAD", "Confrontation directe"),
                    ("WINS", "Nombre de victoires"),
                    ("SCORE_FOR", "Score total marqué"),
                    ("SCORE_AGAINST_ASC", "Score total encaissé (croissant)"),
                    ("FORM", "Forme récente"),
                    ("SEED", "Tête de série"),
                    ("ALPHABETICAL", "Ordre alphabétique"),
                    ("DRAW_LOTS", "Tirage au sort"),
                    ("MANUAL", "Décision de l'arbitre"),
                ],
                max_length=20,
            ),
        ),
    ]
