# Generated by Django 5.2.17 on 2026-09-10 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("championships", "0001_initial"),
        ("participations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Phase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="créé le"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("LEAGUE", "Phase de ligue"),
                            ("SEMI_FINAL", "Demi-finale"),
                            ("FINAL", "Finale"),
                            ("THIRD_PLACE", "Petite finale"),
                            ("PLAYOFF", "Play-off"),
                            ("BARRAGE", "Barrage"),
                            ("CUSTOM", "Personnalisée"),
                        ],
                        default="LEAGUE",
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="nom")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=1, verbose_name="ordre"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("IN_PROGRESS", "En cours"),
                            ("COMPLETED", "Terminée"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "championship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phases",
                        to="championships.championship",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vide = phase commune à toutes les divisions.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phases",
                        to="championships.division",
                    ),
                ),
            ],
            options={
                "verbose_name": "phase",
                "verbose_name_plural": "phases",
                "ordering": ["championship", "division", "order"],
            },
        ),
        migrations.CreateModel(
            name="Matchday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="créé le"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
                ("number", models.PositiveSmallIntegerField(verbose_name="numéro")),
                (
                    "name",
                    models.CharField(blank=True, max_length=80, verbose_name="nom"),
                ),
                (
                    "scheduled_date",
                    models.DateField(blank=True, null=True, verbose_name="date prévue"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "À planifier"),
                            ("SCHEDULED", "Planifiée"),
                            ("IN_PROGRESS", "En cours"),
                            ("COMPLETED", "Terminée"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matchdays",
                        to="competition.phase",
                    ),
                ),
            ],
            options={
                "verbose_name": "journée",
                "verbose_name_plural": "journées",
                "ordering": ["phase", "number"],
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="créé le"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
                (
                    "pair_key",
                    models.CharField(db_index=True, editable=False, max_length=40),
                ),
                (
                    "leg",
                    models.PositiveSmallIntegerField(default=1, verbose_name="manche"),
                ),
                (
                    "scheduled_date",
                    models.DateField(blank=True, null=True, verbose_name="date prévue"),
                ),
                (
                    "scheduled_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="heure prévue"
                    ),
                ),
                (
                    "played_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="joué le"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Programmé"),
                            ("UPCOMING", "À venir"),
                            ("IN_PROGRESS", "En cours"),
                            ("COMPLETED", "Terminé"),
                            ("POSTPONED", "Reporté"),
                            ("CANCELLED", "Annulé"),
                            ("FORFEIT", "Forfait"),
                            ("DISPUTED", "Litige"),
                        ],
                        db_index=True,
                        default="SCHEDULED",
                        max_length=16,
                    ),
                ),
                (
                    "result_status",
                    models.CharField(
                        choices=[
                            ("NONE", "Aucun"),
                            ("SUBMITTED", "Soumis"),
                            ("CONFIRMED", "Confirmé"),
                            ("VALIDATED", "Validé"),
                            ("DISPUTED", "Litige"),
                            ("REJECTED", "Rejeté"),
                        ],
                        db_index=True,
                        default="NONE",
                        max_length=16,
                    ),
                ),
                (
                    "outcome_type",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("FORFEIT_P1", "Forfait joueur 1"),
                            ("FORFEIT_P2", "Forfait joueur 2"),
                            ("DOUBLE_FORFEIT", "Double forfait"),
                            ("BYE", "Exempt"),
                            ("NOT_PLAYED", "Non joué"),
                        ],
                        default="NORMAL",
                        max_length=16,
                    ),
                ),
                (
                    "score1",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="score joueur 1"
                    ),
                ),
                (
                    "score2",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="score joueur 2"
                    ),
                ),
                ("entered_at", models.DateTimeField(blank=True, null=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("postponed_from", models.DateField(blank=True, null=True)),
                ("reschedule_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "source",
                    models.CharField(
                        choices=[("GENERATED", "Généré"), ("MANUAL", "Manuel")],
                        default="GENERATED",
                        max_length=12,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "counts_for_standings",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "championship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="championships.championship",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matches",
                        to="championships.division",
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches_entered",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matches_as_p1",
                        to="participations.championshipparticipation",
                    ),
                ),
                (
                    "player2",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vide = joueur exempt (bye).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matches_as_p2",
                        to="participations.championshipparticipation",
                    ),
                ),
                (
                    "referee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches_refereed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches_validated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches_won",
                        to="participations.championshipparticipation",
                    ),
                ),
                (
                    "matchday",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches",
                        to="competition.matchday",
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="competition.phase",
                    ),
                ),
            ],
            options={
                "verbose_name": "match",
                "verbose_name_plural": "matchs",
                "ordering": ["championship", "division", "id"],
            },
        ),
        migrations.CreateModel(
            name="ResultSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="créé le"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
                ("score1", models.IntegerField(verbose_name="score joueur 1")),
                ("score2", models.IntegerField(verbose_name="score joueur 2")),
                (
                    "outcome_type",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("FORFEIT_P1", "Forfait joueur 1"),
                            ("FORFEIT_P2", "Forfait joueur 2"),
                            ("DOUBLE_FORFEIT", "Double forfait"),
                            ("BYE", "Exempt"),
                            ("NOT_PLAYED", "Non joué"),
                        ],
                        default="NORMAL",
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("PLAYER", "Joueur"),
                            ("OPPONENT", "Adversaire"),
                            ("REFEREE", "Arbitre"),
                            ("ADMIN", "Administrateur"),
                            ("IMPORT", "Import"),
                        ],
                        max_length=12,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("is_superseded", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claimed_winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="participations.championshipparticipation",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="competition.match",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="result_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by_participation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="result_submissions",
                        to="participations.championshipparticipation",
                    ),
                ),
            ],
            options={
                "verbose_name": "saisie de résultat",
                "verbose_name_plural": "saisies de résultat",
                "ordering": ["match", "submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="TieResolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="créé le"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
                (
                    "ordered_result",
                    models.JSONField(
                        default=list,
                        help_text="Liste ordonnée d'identifiants de participations.",
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                (
                    "championship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tie_resolutions",
                        to="championships.championship",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tie_resolutions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tie_resolutions",
                        to="championships.division",
                    ),
                ),
                (
                    "participations",
                    models.ManyToManyField(
                        related_name="tie_resolutions",
                        to="participations.championshipparticipation",
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tie_resolutions",
                        to="competition.phase",
                    ),
                ),
            ],
            options={
                "verbose_name": "résolution d'égalité",
                "verbose_name_plural": "résolutions d'égalité",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="phase",
            constraint=models.UniqueConstraint(
                fields=("division", "kind", "order"),
                name="uniq_phase_per_division_kind_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="matchday",
            constraint=models.UniqueConstraint(
                fields=("phase", "number"), name="uniq_matchday_number"
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["championship", "division", "status"],
                name="competition_champio_a44266_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["result_status"], name="competition_result__f7f97a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["scheduled_date"], name="competition_schedul_5b2315_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("player2__isnull", True),
                    models.Q(("player1", models.F("player2")), _negated=True),
                    _connector="OR",
                ),
                name="match_no_self_play",
            ),
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.UniqueConstraint(
                fields=("phase", "leg", "pair_key"),
                name="uniq_match_pair_per_phase_leg",
            ),
        ),
        migrations.AddConstraint(
            model_name="resultsubmission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_superseded", False)),
                fields=("match", "submitted_by"),
                name="uniq_active_submission_per_user_match",
            ),
        ),
    ]
