# Generated by Django 5.2.17 on 2026-09-11 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("championships", "0004_alter_championshipsettings_finals_format_and_more"),
        ("competition", "0001_initial"),
        ("participations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["phase", "counts_for_standings", "result_status"],
                name="match_standings_lookup_idx",
            ),
        ),
    ]
