# Generated by Django 5.2.17 on 2026-09-15 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "championships",
            "0005_alter_promotionrelegationrule_source_division_and_more",
        ),
        ("competition", "0002_match_match_standings_lookup_idx"),
        ("participations", "0002_alter_championshipparticipation_division"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="division",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="matches",
                to="championships.division",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="player1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="matches_as_p1",
                to="participations.championshipparticipation",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="player2",
            field=models.ForeignKey(
                blank=True,
                help_text="Vide = joueur exempt (bye).",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="matches_as_p2",
                to="participations.championshipparticipation",
            ),
        ),
    ]
