# Generated by Django 5.2.17 on 2026-09-10 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("championships", "0001_initial"),
        ("competition", "0001_initial"),
        ("participations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bracket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="créé le"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
                (
                    "size",
                    models.PositiveSmallIntegerField(
                        verbose_name="nombre de qualifiés"
                    ),
                ),
                ("format", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("READY", "Prêt"),
                            ("IN_PROGRESS", "En cours"),
                            ("COMPLETED", "Terminé"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "championship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brackets",
                        to="championships.championship",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brackets",
                        to="championships.division",
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brackets",
                        to="competition.phase",
                    ),
                ),
            ],
            options={
                "verbose_name": "tableau final",
                "verbose_name_plural": "tableaux finaux",
            },
        ),
        migrations.CreateModel(
            name="BracketSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="créé le"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
                (
                    "round_index",
                    models.PositiveSmallIntegerField(help_text="0 = premier tour."),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("seed", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("is_third_place", models.BooleanField(default=False)),
                (
                    "bracket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="finals.bracket",
                    ),
                ),
                (
                    "match",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bracket_slot",
                        to="competition.match",
                    ),
                ),
                (
                    "participation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bracket_slots",
                        to="participations.championshipparticipation",
                    ),
                ),
                (
                    "source_slot_lose",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feeds_lose",
                        to="finals.bracketslot",
                    ),
                ),
                (
                    "source_slot_win",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feeds_win",
                        to="finals.bracketslot",
                    ),
                ),
            ],
            options={
                "verbose_name": "emplacement de tableau",
                "verbose_name_plural": "emplacements de tableau",
                "ordering": ["bracket", "round_index", "position"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("bracket", "round_index", "position"),
                        name="uniq_slot_position",
                    )
                ],
            },
        ),
    ]
