# Generated by Django 5.2.17 on 2026-09-11 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0001_initial"),
        ("finals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bracketslot",
            name="match",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bracket_slots",
                to="competition.match",
            ),
        ),
    ]
