# Generated by Django 5.2.17 on 2026-09-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0001_initial"),
        ("finals", "0002_alter_bracketslot_match"),
        ("participations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bracketslot",
            name="uniq_slot_position",
        ),
        migrations.AddConstraint(
            model_name="bracketslot",
            constraint=models.UniqueConstraint(
                fields=("bracket", "round_index", "position", "is_third_place"),
                name="uniq_slot_position",
            ),
        ),
    ]
