# Generated by Django 5.2.17 on 2026-09-10 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("championships", "0001_initial"),
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChampionshipParticipation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="créé le"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
                (
                    "seed",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="tête de série"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REGISTERED", "Inscrit"),
                            ("CONFIRMED", "Confirmé"),
                            ("ACTIVE", "Actif"),
                            ("WITHDRAWN", "Retiré"),
                            ("DISQUALIFIED", "Disqualifié"),
                            ("FORFEIT_ALL", "Forfait général"),
                        ],
                        db_index=True,
                        default="REGISTERED",
                        max_length=16,
                    ),
                ),
                (
                    "entry_origin",
                    models.CharField(
                        choices=[
                            ("NEW", "Nouvelle inscription"),
                            ("PROMOTED_FROM", "Promu"),
                            ("RELEGATED_FROM", "Relégué"),
                            ("KEPT", "Maintenu"),
                            ("MANUAL", "Placement manuel"),
                        ],
                        default="NEW",
                        max_length=16,
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("final_rank", models.PositiveIntegerField(blank=True, null=True)),
                ("final_points", models.IntegerField(blank=True, null=True)),
                ("final_played", models.PositiveIntegerField(blank=True, null=True)),
                ("final_wins", models.PositiveIntegerField(blank=True, null=True)),
                ("final_draws", models.PositiveIntegerField(blank=True, null=True)),
                ("final_losses", models.PositiveIntegerField(blank=True, null=True)),
                ("final_score_for", models.IntegerField(blank=True, null=True)),
                ("final_score_against", models.IntegerField(blank=True, null=True)),
                ("final_score_diff", models.IntegerField(blank=True, null=True)),
                (
                    "promotion_outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PROMOTED", "Promu"),
                            ("RELEGATED", "Relégué"),
                            ("STAYED", "Maintenu"),
                            ("QUALIFIED_FINALS", "Qualifié en phase finale"),
                            ("FINALIST", "Finaliste"),
                            ("CHAMPION", "Champion"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "resulting_division_carryover_key",
                    models.SlugField(blank=True, max_length=40),
                ),
                (
                    "championship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="championships.championship",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participations",
                        to="championships.division",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participations",
                        to="players.player",
                    ),
                ),
                (
                    "source_participation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="next_participations",
                        to="participations.championshipparticipation",
                    ),
                ),
            ],
            options={
                "verbose_name": "participation",
                "verbose_name_plural": "participations",
                "ordering": ["championship", "division", "seed"],
                "indexes": [
                    models.Index(
                        fields=["championship", "division", "status"],
                        name="participati_champio_5074f8_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("championship", "player"),
                        name="uniq_player_per_championship",
                    )
                ],
            },
        ),
    ]
