# Generated by Django 5.2.17 on 2026-09-15 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "championships",
            "0005_alter_promotionrelegationrule_source_division_and_more",
        ),
        ("participations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="championshipparticipation",
            name="division",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="participations",
                to="championships.division",
            ),
        ),
    ]
