# Generated by Django 5.2.17 on 2026-09-10 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="créé le"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="nom")),
                (
                    "display_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="nom affiché"
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="players/"),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="date de naissance"
                    ),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=64, verbose_name="pays"),
                ),
                (
                    "club",
                    models.CharField(blank=True, max_length=120, verbose_name="club"),
                ),
                ("bio", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="players_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="player",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "joueur",
                "verbose_name_plural": "joueurs",
                "ordering": ["last_name", "first_name"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="players_pla_is_acti_90e805_idx"
                    )
                ],
            },
        ),
    ]
