# Generated by Django 5.2.17 on 2026-09-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="scrabblego_id",
            field=models.CharField(
                blank=True,
                help_text="Identifiant unique du joueur sur l'application ScrabbleGO, affiché publiquement (classements, adversaires) pour permettre aux joueurs de s'y retrouver d'une division à l'autre.",
                max_length=64,
                verbose_name="identifiant ScrabbleGO",
            ),
        ),
    ]
