# Generated by Django 5.2.17 on 2026-09-10 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("championships", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="créé le"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("MATCH_TODAY", "Match aujourd'hui"),
                            ("RESULT_RECORDED", "Résultat enregistré"),
                            ("RESULT_NEEDS_CONFIRMATION", "Résultat à confirmer"),
                            ("RESULT_DISPUTED", "Résultat en litige"),
                            ("MATCH_LATE", "Match en retard"),
                            ("RANK_UPDATE", "Classement mis à jour"),
                            ("PROMOTION_ZONE", "Zone de promotion"),
                            ("RELEGATION_ZONE", "Zone de relégation"),
                            ("FINALS_QUALIFIED", "Qualifié en phase finale"),
                            ("RULE_CHANGED", "Règle modifiée"),
                            ("GENERIC", "Information"),
                        ],
                        default="GENERIC",
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("link_url", models.CharField(blank=True, max_length=300)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Basse"),
                            ("NORMAL", "Normale"),
                            ("HIGH", "Haute"),
                        ],
                        default="NORMAL",
                        max_length=8,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "championship",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="championships.championship",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read", "created_at"],
                        name="notificatio_recipie_86ea8b_idx",
                    )
                ],
            },
        ),
    ]
