# Generated by Django 5.2.17 on 2026-09-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("MATCH_TODAY", "Match aujourd'hui"),
                    ("RESULT_RECORDED", "Résultat enregistré"),
                    ("RESULT_NEEDS_CONFIRMATION", "Résultat à confirmer"),
                    ("RESULT_DISPUTED", "Résultat en litige"),
                    ("DISPUTE_TO_RESOLVE", "Litige à trancher"),
                    ("MATCH_LATE", "Match en retard"),
                    ("MATCH_LATE_ADMIN", "Match en retard (à relancer)"),
                    ("RANK_UPDATE", "Classement mis à jour"),
                    ("PROMOTION_ZONE", "Zone de promotion"),
                    ("RELEGATION_ZONE", "Zone de relégation"),
                    ("FINALS_QUALIFIED", "Qualifié en phase finale"),
                    ("RULE_CHANGED", "Règle modifiée"),
                    ("GENERIC", "Information"),
                ],
                default="GENERIC",
                max_length=32,
            ),
        ),
    ]
